In [1]:
"""import packages you need"""
import numpy as np
import pandas as pd

In [2]:
### read data from an excel file 
df1 = pd.read_excel('Machine Learning Data.xlsx')
display(df1.head())

### drop the first colums named `Explanation`, you can ues
# df1.dropna(how='any', axis=1, inplace = True) # drop any column (axis=1) that has Nan value in 
df1.drop('Explanation', inplace = True, axis = 'columns')

print(df1.shape)
df1.head()

,Explanation,Frequency,Speed,Amplitude,Passes,Focal Position,Depth,Angle
0,Midplane Focus,600.0,15.0,0.5,20,93.87,620.696667,44.100000
1,NaN,600.0,15.0,0.5,40,93.87,686.676667,40.000000
2,NaN,600.0,15.0,0.5,60,93.87,710.660000,38.110000
3,NaN,600.0,15.0,0.5,80,93.87,730.803333,37.556667
4,NaN,600.0,15.0,0.5,100,93.87,736.666667,37.440000

(189, 7)

   Frequency  Speed  Amplitude  Passes  Focal Position       Depth      Angle
0      600.0   15.0        0.5      20           93.87  620.696667  44.100000
1      600.0   15.0        0.5      40           93.87  686.676667  40.000000
2      600.0   15.0        0.5      60           93.87  710.660000  38.110000
3      600.0   15.0        0.5      80           93.87  730.803333  37.556667
4      600.0   15.0        0.5     100           93.87  736.666667  37.440000

In [4]:
### Get the correlation between different features in the data 
df1.corr(method='pearson')

,Frequency,Speed,Amplitude,Passes,Focal Position,Depth,Angle
Frequency,1.000000,0.723005,-0.463144,0.293217,-0.263918,-0.266211,-0.125346
Speed,0.723005,1.000000,-0.387851,0.382337,-0.190791,-0.315142,0.056314
Amplitude,-0.463144,-0.387851,1.000000,-0.450674,0.376932,-0.151250,0.543039
Passes,0.293217,0.382337,-0.450674,1.000000,-0.387754,0.311235,-0.205304
Focal Position,-0.263918,-0.190791,0.376932,-0.387754,1.000000,-0.342300,0.461602
Depth,-0.266211,-0.315142,-0.151250,0.311235,-0.342300,1.000000,-0.503174
Angle,-0.125346,0.056314,0.543039,-0.205304,0.461602,-0.503174,1.000000

In [5]:
df1.corr(method='spearman')

,Frequency,Speed,Amplitude,Passes,Focal Position,Depth,Angle
Frequency,1.000000,0.738290,-0.582861,0.323237,-0.098904,-0.208324,-0.078832
Speed,0.738290,1.000000,-0.458491,0.390174,0.026116,-0.293751,0.085561
Amplitude,-0.582861,-0.458491,1.000000,-0.439879,0.115544,-0.024891,0.493547
Passes,0.323237,0.390174,-0.439879,1.000000,-0.258138,0.350555,-0.206807
Focal Position,-0.098904,0.026116,0.115544,-0.258138,1.000000,-0.208497,0.087028
Depth,-0.208324,-0.293751,-0.024891,0.350555,-0.208497,1.000000,-0.594097
Angle,-0.078832,0.085561,0.493547,-0.206807,0.087028,-0.594097,1.000000

In [6]:
df1.corr(method='kendall')

,Frequency,Speed,Amplitude,Passes,Focal Position,Depth,Angle
Frequency,1.000000,0.635803,-0.473124,0.249639,-0.086737,-0.180495,-0.045658
Speed,0.635803,1.000000,-0.374342,0.299816,0.016853,-0.225976,0.063854
Amplitude,-0.473124,-0.374342,1.000000,-0.374556,0.093173,0.003085,0.378708
Passes,0.249639,0.299816,-0.374556,1.000000,-0.229776,0.256139,-0.138409
Focal Position,-0.086737,0.016853,0.093173,-0.229776,1.000000,-0.154135,0.060560
Depth,-0.180495,-0.225976,0.003085,0.256139,-0.154135,1.000000,-0.458360
Angle,-0.045658,0.063854,0.378708,-0.138409,0.060560,-0.458360,1.000000