# Here we extract table of parameters based on desired parameters

In [1]:
"""import packages you need"""
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 

from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.utils import shuffle

# from xgboost import XGBRegressor
from IPython.display import clear_output
import torch
import torch.nn as nn
from torch.utils.data import Dataset
torch.manual_seed(20210614)

## Add the conditions that you want to filter the table based on as conditions to the following funtion

In [38]:
# def ParamTable_condition(Data, angles, Ang_diff):
#         result = []
#         indexes = []
#         for angle in angles: 
#             condition1 = (np.abs(Data.Angle - angle) <= Ang_diff)
#             condition2 = (np.abs(Data.Focal_Position - 93.2) <= (0.01))
#             condition3 = ((Data.Speed * 1000 / Data.Frequency) <= 35)
#             index = (np.where(condition1 & condition2 & condition3))[0]
#             indexes.extend(index.tolist())
#         for i in indexes:
#             case = np.r_[i, ((Data.iloc[i]).round(3))]
#             result.append(case)  
#         DATA = np.array(result)    
#         df_results = pd.DataFrame(DATA, columns = 
#     ['index','Frequency', 'Speed', 'Amplitude', 'Passes', 'Focal_Position', 'Depth',
#        'Angle'])
#         return df_results

In [195]:
### --------- Read the GAN data and find the combination you want:
# df = pd.read_csv('RawData/rscl_NNPred_GAN02.csv')
# df = pd.read_csv('RawData/Aug30/rscl_GAN02_Aug30.csv')

# result = ParamTable_condition(df,[50], 0.5)
# result[(result > 0).all(1)]

# result.to_csv(r'../Data/Aug11/Angle50_NNPred_GAN02.csv', header=True, index = False)

In [65]:
# def ParamTable_trapizoid(Data, angles, depth, ang_diff, no_pass):
#         result = []
#         indexes = []
#         for angle in angles: 
#             condition0 = (Data.Passes <= no_pass)
#             condition1 = (Data.Bot_width > 0)
#             condition2 = (Data.Top_width > 0) 
#             condition3 = (Data.Depth < depth) 
#             radian = np.arctan((Data.Top_width-Data.Bot_width)/(2* Data.Depth))
#             condition4 = (np.abs(np.degrees(radian) - angle) <= ang_diff)
#             index = (np.where(condition0 & condition1 & condition2 & condition3 &
#                               condition4 ))[0]
#             indexes.extend(index.tolist())

#         for i in indexes:
#             radian2 = np.arctan((Data.iloc[i].Top_width-Data.iloc[i].Bot_width)/(2* Data.iloc[i].Depth))
#             case = np.r_[round(np.degrees(radian2),2), (Data.iloc[i].Frequency / 40. ), ((Data.iloc[i]).round(3))]
#             result.append(case)  
#         DATA = np.array(result)    
#         df_results = pd.DataFrame(DATA,
#                                   columns = 
#     ['angle', 'Speed', 'Frequency','Amplitude', 'Passes', 'Focal_Position', 'Depth',
#        'Top_width', 'Bot_width'])
#         return df_results

In [194]:
# Data = pd.read_csv('RawData/two_widths/resclGRID.csv')
# # Data.keys()
# df = Data.drop(['Speed'], axis = 'columns')

# # result = ParamTable_trapizoid(df,[5,6, 7, 8, 9,10], 1000, 2, 90)
# # result = ParamTable_trapizoid(df,[20], 300, 2, 10)
# result = ParamTable_trapizoid(df,[30], 150, 2, 10)


# result[(result > 0).all(1)]

# # result.to_csv(r'RawData/two_widths/TestData/Trap_minAng_Grid.csv', header=True, index = False)
# # result.to_csv(r'RawData/two_widths/TestData/Trap_Ang20_Grid.csv', header=True, index = False)
# result.to_csv(r'RawData/two_widths/TestData/Trap_Ang30_Grid.csv', header=True, index = False)

# result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,31.80,10.00,400.0,0.5,10.0,91.676,139.209,602.162,429.564
1,31.06,11.25,450.0,0.5,10.0,91.676,133.755,574.510,413.420
2,31.76,12.50,500.0,0.5,10.0,91.676,122.590,556.876,405.090
3,28.12,13.75,550.0,0.4,10.0,91.676,149.791,442.184,282.062
4,29.97,15.00,600.0,0.4,10.0,91.676,131.368,432.834,281.342
...,...,...,...,...,...,...,...,...,...
136,31.20,40.00,1600.0,1.0,10.0,93.200,101.864,976.147,852.771
137,30.71,40.00,1600.0,1.1,10.0,92.819,107.668,1064.503,936.582
138,30.30,40.00,1600.0,1.1,10.0,93.200,102.373,1056.766,937.140
139,29.92,40.00,1600.0,1.2,10.0,92.819,109.212,1145.208,1019.528
140,29.32,40.00,1600.0,1.2,10.0,93.200,103.682,1133.697,1017.237

In [69]:
GAN_result = pd.read_csv('RawData/two_widths/GAN_tuned.csv')

# GAN_result.keys()
result = ParamTable_trapizoid(GAN_result,[5,6, 7, 8, 9,10], 1000, 3, 90)
result[(result > 0).all(1)]
result.to_csv(r'RawData/two_widths/TestData/Trap_minAng_GAN.csv', header=True, index = False)
result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,4.87,39.939325,1597.573,0.389,15.143,93.166,134.482,395.243,372.347
1,4.87,39.939325,1597.573,0.389,15.143,93.166,134.482,395.243,372.347
2,8.54,27.687600,1107.504,0.282,21.383,91.699,42.447,439.729,426.977
3,4.87,39.939325,1597.573,0.389,15.143,93.166,134.482,395.243,372.347
4,8.54,27.687600,1107.504,0.282,21.383,91.699,42.447,439.729,426.977
5,8.54,27.687600,1107.504,0.282,21.383,91.699,42.447,439.729,426.977
6,11.51,28.777250,1151.090,0.715,14.875,92.312,103.042,597.853,555.874
7,8.54,27.687600,1107.504,0.282,21.383,91.699,42.447,439.729,426.977
8,12.27,39.549350,1581.974,0.608,15.166,92.493,91.117,499.440,459.803
9,11.51,28.777250,1151.090,0.715,14.875,92.312,103.042,597.853,555.874
10,12.72,39.999375,1599.975,0.095,15.019,93.200,293.942,133.039,0.301
11,12.31,25.575975,1023.039,0.428,12.461,92.843,198.357,457.293,370.715
12,8.54,27.687600,1107.504,0.282,21.383,91.699,42.447,439.729,426.977
13,12.70,20.481600,819.264,0.199,16.962,93.200,490.017,221.970,1.175

In [197]:
GAN_result = pd.read_csv('RawData/two_widths/GAN_tuned.csv')

# GAN_result.keys()
# result = ParamTable_trapizoid(GAN_result,[40], 500, 2, 30)
result = ParamTable_trapizoid(GAN_result,[20], 200, 2, 20)


result[(result > 0).all(1)]
# result.to_csv(r'RawData/two_widths/TestData/Trap_Ang40_GAN.csv', header=True, index = False)
# result.to_csv(r'RawData/two_widths/TestData/Trap_Ang30_GAN.csv', header=True, index = False)
result.to_csv(r'RawData/two_widths/TestData/Trap_Ang20_GAN.csv', header=True, index = False)



result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,21.94,10.283975,411.359,0.614,19.357,91.701,118.721,680.487,584.831
1,18.15,14.577650,583.106,0.310,13.607,92.339,160.426,472.735,367.532
2,19.35,22.433900,897.356,0.969,12.485,92.408,144.479,898.524,797.062
3,19.32,31.955775,1278.231,0.894,16.017,92.012,83.192,680.660,622.331
4,20.85,17.207775,688.311,0.267,17.963,91.851,112.801,493.536,407.607
5,18.84,38.521675,1540.867,0.292,14.409,92.259,138.726,323.201,228.531
6,21.26,36.388775,1455.551,0.600,12.585,92.740,183.488,557.559,414.790
7,19.18,29.510600,1180.424,0.681,13.794,92.463,199.231,611.140,472.526
8,18.14,27.201250,1088.050,0.829,11.833,92.592,193.895,748.123,621.061
9,21.90,9.794675,391.787,0.267,19.161,91.734,172.738,576.330,437.422
10,21.43,25.435350,1017.414,0.911,15.561,92.378,184.781,855.286,710.222
11,19.35,16.070375,642.815,0.309,17.758,91.899,102.935,521.280,448.995
12,20.03,37.125175,1485.007,0.740,12.471,93.172,193.614,668.265,527.124
13,18.50,36.231900,1449.276,0.810,12.569,92.998,186.743,682.958,557.991
14,19.16,25.867150,1034.686,0.700,13.870,92.380,198.773,652.090,513.959
15,21.97,39.930325,1597.213,0.546,12.534,92.882,171.833,520.445,381.813
16,21.83,22.647475,905.899,0.268,17.703,91.906,161.740,394.352,264.801
17,18.65,33.937025,1357.481,0.790,12.816,93.087,195.375,692.921,561.048
18,20.52,20.750075,830.003,0.639,18.572,92.023,164.694,669.337,546.024
19,20.39,39.642350,1585.694,0.848,14.131,92.409,168.625,673.840,548.491
20,20.32,39.952400,1598.096,0.597,13.228,93.187,198.899,559.362,412.071
21,20.67,27.672200,1106.888,0.253,12.697,92.318,175.286,264.871,132.609
22,19.18,29.260225,1170.409,0.537,14.412,92.208,175.676,515.187,392.951
23,21.49,31.106675,1244.267,0.473,14.457,92.237,172.318,444.081,308.388
24,20.00,39.886350,1595.454,0.378,13.595,92.538,143.156,367.652,263.460
25,21.21,10.099750,403.990,0.546,19.639,91.676,121.369,677.845,583.662
26,18.46,16.292750,651.710,0.328,11.789,92.618,168.971,431.240,318.411
27,18.15,28.165700,1126.628,0.733,13.452,92.417,174.593,671.353,556.867
28,20.48,39.394400,1575.776,0.238,14.303,92.309,135.666,275.996,174.672
29,19.00,25.298875,1011.955,0.888,13.007,92.464,175.981,822.168,700.998
30,18.99,21.496925,859.877,0.290,11.531,92.459,180.025,296.971,173.072
31,18.44,27.277500,1091.100,0.613,13.016,92.340,194.212,556.814,427.304
32,18.22,22.204325,888.173,0.371,16.498,92.029,179.495,479.863,361.719
33,19.56,23.314150,932.566,0.262,18.674,91.821,171.426,421.718,299.905
34,21.81,29.220525,1168.821,0.291,18.637,91.841,179.866,352.070,208.149

In [200]:
def ParamTable_triang(Data, angles, depth, ang_diff, no_pass):
        result = []
        indexes = []
        for angle in angles: 
            condition0 = (Data.Passes < no_pass)
#             condition0 = (Data.Bot_width > 0)
            condition1 = (np.abs(Data.Bot_width) <= 10)
            condition2 = (Data.Top_width > 0) 
            condition3 = (Data.Depth > depth) 
            radian = np.arctan((Data.Top_width)/(2* Data.Depth))
            condition4 = (np.abs(np.degrees(radian) - angle) <= ang_diff)
            index = (np.where(condition0 & condition1 & condition2 & condition3 &
                              condition4 ))[0]
            indexes.extend(index.tolist())

        for i in indexes:
            radian2 = np.arctan((Data.iloc[i].Top_width-Data.iloc[i].Bot_width)/(2* Data.iloc[i].Depth))
            case = np.r_[round(np.degrees(radian2),2),Data.iloc[i].Frequency / 40., ((Data.iloc[i]).round(3))]
            result.append(case)  
        DATA = np.array(result)    
        df_results = pd.DataFrame(DATA, columns = 
    ['angle', 'Speed','Frequency', 'Amplitude', 'Passes', 'Focal_Position', 'Depth',
       'Top_width', 'Bot_width'])
        return df_results

In [203]:
Data = pd.read_csv('RawData/two_widths/resclGRID.csv')
df = Data.drop(['Speed'], axis = 'columns')


result = ParamTable_triang(df,[20], 1000, 2, 120)
# result = ParamTable_triang(df,[30], 900, 2, 120)
result[(result > 0).all(1)]

result.to_csv(r'RawData/two_widths/TestData/DeepTriang_Ang20Grid.csv', header=True, index = False)

result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,22.16,5.00,200.0,0.8,55.0,92.057,1059.863,854.296,-9.131
1,21.72,5.00,200.0,0.8,90.0,92.057,1101.395,869.525,-7.820
2,21.64,5.00,200.0,0.8,95.0,92.057,1103.284,871.873,-3.390
3,21.55,5.00,200.0,0.8,100.0,92.057,1105.356,874.159,0.954
4,21.47,5.00,200.0,0.8,105.0,92.057,1107.283,876.589,5.754
5,21.58,5.00,200.0,0.9,75.0,92.438,1157.358,920.674,5.229
6,21.55,5.00,200.0,0.9,80.0,92.438,1166.029,923.116,2.055
7,21.53,5.00,200.0,0.9,85.0,92.438,1173.899,925.343,-0.763
8,21.50,5.00,200.0,0.9,90.0,92.438,1180.950,927.115,-3.287
9,21.48,5.00,200.0,0.9,95.0,92.438,1187.143,928.839,-5.356
10,21.44,5.00,200.0,0.9,100.0,92.438,1193.060,930.400,-6.867
11,21.40,5.00,200.0,0.9,105.0,92.438,1199.215,931.864,-8.156
12,21.36,5.00,200.0,0.9,110.0,92.438,1205.385,933.336,-9.274
13,21.84,6.25,250.0,0.9,100.0,92.438,1147.057,926.163,6.541
14,21.80,6.25,250.0,0.9,105.0,92.438,1153.075,927.544,5.153
15,21.75,6.25,250.0,0.9,110.0,92.438,1158.864,928.975,4.222
16,21.70,6.25,250.0,0.9,115.0,92.438,1164.427,930.075,3.531

In [206]:
GAN_result = pd.read_csv('RawData/two_widths/GANtune_NNPRed.csv')


result = ParamTable_triang(GAN_result,[30], 200, 2, 200)
# result = ParamTable_triang(GAN_result,[20], 850, 2, 100)
result[(result > 0).all(1)]

result.to_csv(r'RawData/two_widths/TestData/Triang_Ang30GAN.csv', header=True, index = False)
# result.to_csv(r'RawData/two_widths/TestData/DeepTriang_Ang20GAN.csv', header=True, index = False)


result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,32.17,37.152800,1486.112,0.201,19.113,92.040,219.629,273.016,-3.307
1,29.80,19.877200,795.088,0.164,12.709,93.200,235.861,275.990,5.824
2,29.87,18.674500,746.980,0.125,11.169,92.946,206.627,242.042,4.685
3,29.02,23.239450,929.578,0.228,20.827,91.786,321.492,350.181,-6.468
4,29.92,12.797250,511.890,0.206,16.625,91.945,246.296,292.666,9.167
5,30.35,20.208500,808.340,0.176,12.124,93.199,233.222,276.976,3.885
6,29.62,37.530500,1501.220,0.186,16.934,92.225,214.448,240.818,-2.985
7,29.74,19.136400,765.456,0.110,14.020,93.169,209.283,242.149,3.026
8,29.57,19.848350,793.934,0.140,10.907,93.072,205.727,234.807,1.348
9,28.52,15.930650,637.226,0.203,15.576,92.027,242.265,268.014,4.663
10,30.45,32.171350,1286.854,0.186,17.126,91.947,218.089,251.339,-5.079
11,31.82,20.467100,818.684,0.201,17.772,91.961,247.599,299.052,-8.219
12,30.38,18.964175,758.567,0.106,12.489,93.200,205.575,247.310,6.326
13,27.63,21.538200,861.528,0.463,26.013,92.201,448.831,479.152,9.359
14,31.01,19.765750,790.630,0.150,11.856,93.198,216.384,265.694,5.520

In [208]:
Data = pd.read_csv('RawData/two_widths/resclGRID.csv')
df = Data.drop(['Speed'], axis = 'columns')


result = ParamTable_triang(df,[40, 50], 100, 5, 200)
result[(result > 0).all(1)]
result.to_csv(r'RawData/two_widths/TestData/Triang_Ang35-55Grid.csv', header=True, index = False)
result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,40.88,12.50,500.0,0.2,10.0,92.438,174.346,304.418,2.635
1,39.03,12.50,500.0,0.2,10.0,92.819,198.417,329.943,8.273
2,35.76,12.50,500.0,0.2,15.0,92.438,215.373,310.055,-0.119
3,35.26,13.75,550.0,0.2,10.0,92.819,212.085,298.879,-0.962
4,41.99,20.00,800.0,0.1,10.0,92.819,132.324,240.978,2.779
5,37.53,21.25,850.0,0.1,10.0,92.819,149.279,230.569,1.261
6,54.08,12.50,500.0,0.1,15.0,92.819,123.922,351.965,9.840
7,51.52,17.50,700.0,0.1,10.0,92.819,103.550,264.540,3.969
8,46.76,18.75,750.0,0.1,10.0,92.819,116.684,251.805,3.624

In [210]:
GAN_result = pd.read_csv('RawData/two_widths/GANtune_NNPRed.csv')


result = ParamTable_triang(GAN_result,[40, 50], 100, 5, 200)
result[(result > 0).all(1)]
result.to_csv(r'RawData/two_widths/TestData/Triang_Ang35-55GAN.csv', header=True, index = False)
result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,36.37,20.123250,804.930,0.133,11.556,93.183,167.320,249.874,3.383
1,37.05,20.170800,806.832,0.111,11.176,93.129,149.365,227.034,1.531
2,36.16,18.345050,733.802,0.166,13.153,92.179,183.895,269.022,0.234
3,35.01,19.649800,785.992,0.116,11.810,93.196,172.141,246.649,5.521
4,35.15,18.778150,751.126,0.108,12.726,93.200,185.398,270.906,9.835
5,42.24,37.499450,1499.978,0.089,12.984,93.053,107.342,193.021,-1.926
6,35.90,18.650875,746.035,0.084,11.307,93.092,152.311,224.656,4.130
7,38.31,26.753350,1070.134,0.148,12.731,92.349,135.917,224.746,9.949
8,44.87,19.118125,764.725,0.172,17.053,92.336,149.636,290.701,-7.191
9,40.89,19.372925,774.917,0.111,12.723,93.200,150.938,270.796,9.392
10,34.62,19.887450,795.498,0.126,26.840,93.200,217.407,308.861,8.649
11,34.52,18.851225,754.049,0.097,15.956,93.200,189.634,269.528,8.637
12,36.60,38.674425,1546.977,0.064,14.995,93.189,121.912,183.166,2.075
13,38.74,19.927625,797.105,0.136,12.246,93.199,162.734,267.406,6.319
14,43.89,20.011375,800.455,0.131,12.079,93.195,135.462,267.906,7.278
15,39.68,15.203125,608.125,0.137,12.033,92.292,149.417,253.264,5.330
16,36.73,18.848425,753.937,0.091,15.021,93.200,172.426,267.057,9.762
17,40.04,21.184350,847.374,0.114,10.734,92.637,130.663,226.250,6.693
18,34.66,34.367500,1374.700,0.176,18.394,91.781,170.033,244.695,9.550
19,41.92,28.784000,1151.360,0.068,13.350,93.101,110.296,199.511,1.432
20,39.44,18.882300,755.292,0.080,11.585,93.161,137.496,231.096,4.912
21,42.63,18.051225,722.049,0.149,12.902,92.214,143.246,266.445,2.758
22,48.68,18.288625,731.545,0.108,11.037,92.538,110.288,258.348,7.475
23,48.37,19.176025,767.041,0.083,12.445,93.184,109.042,253.395,8.050
24,46.48,17.632475,705.299,0.108,11.478,93.117,114.290,250.560,9.863
25,48.64,18.795625,751.825,0.079,14.373,93.159,113.899,267.627,8.846

In [1]:
# j = 0
# for i in range(53940):
#     if (df.iloc[i].Bot_width < 1) & (df.iloc[i].Bot_width > 0) & (df.iloc[i].Top_width > 0) & (df.iloc[i].Depth> 0) :
#         angle = np.degrees(np.arctan(df.iloc[i].Top_width/(2* df.iloc[i].Depth)))
#         if (df.iloc[i].Depth > 1000) :
# #             if ( 9. < angle < 11 ) :
# #                 print('10: ',i,'  ', df.iloc[i].Depth,'  ',
# #                       np.degrees(np.arctan(df.iloc[i].Top_width/(2* df.iloc[i].Depth))))
# #             if ( 14 < angle < 16 ) :
# #                 print('15: ',i,'  ', df.iloc[i].Depth,'  ',
# #                       np.degrees(np.arctan(df.iloc[i].Top_width/(2* df.iloc[i].Depth))))
# #             if ( 19 < angle < 21 ) :
# #                 print('20: ',i,'  ', df.iloc[i].Depth,'  ',
# #                       np.degrees(np.arctan(df.iloc[i].Top_width/(2* df.iloc[i].Depth))))   
#             if ( 24.5 <= angle <= 25.5 ) :
#                 print('25: ',i,'  ', df.iloc[i].Depth,'  ',
#                       np.degrees(np.arctan(df.iloc[i].Top_width/(2* df.iloc[i].Depth))))    
# #             if ( 29 < angle < 31 ) :
# #                 print('30: ',i,'  ', df.iloc[i].Depth,'  ',
# #                       np.degrees(np.arctan(df.iloc[i].Top_width/(2* df.iloc[i].Depth))))
#                 j += 1
            
# print(j)

In [41]:
def Extract_index(Data, indexes):
        result = []
#         indexes = []
#         for angle in angles: 
#             condition1 = (np.abs(Data.Angle - angle) <= Ang_diff)
#             condition2 = (np.abs(Data.Focal_Position - 93.2) <= (0.01))
#             condition3 = ((Data.Speed * 1000 / Data.Frequency) <= 35)
#             index = (np.where(condition1 & condition2 & condition3))[0]
#             indexes.extend(index.tolist())
        for i in indexes:
            case = np.r_[i, ((Data.iloc[i]).round(3))]
            result.append(case)  
        DATA = np.array(result)    
        df_results = pd.DataFrame(DATA, columns = 
    ['index','Frequency', 'Speed', 'Amplitude', 'Passes', 'Focal_Position', 'Depth',
       'Angle'])
        return df_results

### Finding target dimensions for test

In [32]:
def ParamTable_TargetTrap(Data, angles, depth, top_w, bot_w):
        result = []
        indexes = []
        for angle in angles: 
#             condition0 = (Data.Passes <= no_pass)
            condition0 = (Data.Bot_width > 0)
            condition1 = (np.abs(Data.Bot_width - bot_w) <= 50)
            condition2 = (Data.Top_width > 0)
            condition3 = (np.abs(Data.Top_width - top_w) <= 50)
            condition4 = (Data.Depth > 0)
            condition5 = (np.abs(Data.Depth - depth) <= 50) 
            
#             radian = np.arctan((Data.Top_width-Data.Bot_width)/(2* Data.Depth))
#             condition4 = (np.abs(np.degrees(radian) - angle) <= ang_diff)
            index = (np.where(condition0 & condition1 & condition2 & condition3 &
                              condition4 & condition5 ))[0]
            indexes.extend(index.tolist())

        for i in indexes:
            radian2 = np.arctan((Data.iloc[i].Top_width-Data.iloc[i].Bot_width)/(2* Data.iloc[i].Depth))
            case = np.r_[round(np.degrees(radian2),2), (Data.iloc[i].Frequency / 40. ), ((Data.iloc[i]).round(3))]
            result.append(case)  
        DATA = np.array(result)    
        df_results = pd.DataFrame(DATA,
                                  columns = 
    ['angle', 'Speed', 'Frequency','Amplitude', 'Passes', 'Focal_Position', 'Depth',
       'Top_width', 'Bot_width'])
        return df_results

In [34]:
GAN_result = pd.read_csv('RawData/two_widths/GANtune_NNPRed.csv')

result = ParamTable_TargetTrap(GAN_result,[30], 444.5, 500, 100)


result = result[(result > 0).all(1)]

result.to_csv(r'RawData/two_widths/TestData/Trap_GAN.csv', header=True, index = False)

result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,24.76,17.329925,693.197,0.531,26.0,92.148,448.365,534.795,121.205
1,22.80,21.939450,877.578,0.497,20.0,93.198,443.159,498.748,126.246
2,25.51,39.673750,1586.950,0.459,29.0,93.200,398.319,463.812,83.748
3,21.01,15.106200,604.248,0.530,18.0,93.169,488.654,517.009,141.572
4,23.58,7.914050,316.562,0.441,14.0,93.028,400.492,491.638,142.101
...,...,...,...,...,...,...,...,...,...
60,22.76,22.041350,881.654,0.492,20.0,93.199,443.638,493.902,121.580
61,23.35,26.171650,1046.866,0.462,22.0,93.200,422.875,469.035,103.854
62,22.76,13.416250,536.650,0.530,21.0,92.270,487.569,532.173,123.074
63,22.14,21.464450,858.578,0.455,18.0,93.198,439.031,454.524,97.191
64,22.21,21.887400,875.496,0.451,20.0,93.200,461.482,451.391,74.566

In [35]:
GAN_result

,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,1307.286,0.415,12.0,92.626,210.649292,414.576996,203.429001
1,207.354,0.824,25.0,92.275,839.343689,849.793030,178.927002
2,274.302,0.939,20.0,91.997,644.178528,956.307983,370.972992
3,1582.885,0.348,24.0,93.200,380.007141,351.247986,19.150999
4,827.875,0.387,99.0,93.200,578.846863,396.013000,1.289000
...,...,...,...,...,...,...,...
4995,1006.086,0.370,12.0,93.185,344.499268,368.786987,92.177002
4996,804.104,0.860,160.0,93.200,1004.582275,857.155029,-1.680000
4997,1586.873,0.431,12.0,93.190,227.604309,428.730011,210.639008
4998,825.469,0.338,155.0,93.200,552.183716,349.268005,-0.490000
4999,1582.554,0.567,12.0,93.197,176.489883,568.536987,378.946991

In [27]:
def ParamTable_TargetTriang(Data, angles, depth, top_w):
        result = []
        indexes = []
        for angle in angles: 
#             condition0 = (Data.Passes < no_pass)
            condition0 = (Data.Bot_width > 0)
            condition1 = (np.abs(Data.Bot_width) <= 10)
            condition2 = (Data.Top_width > 0) 
            condition3 = (np.abs(Data.Top_width-top_w) <= 50)
            condition4 = (Data.Depth > 0) 
            condition5 = (np.abs(Data.Depth-depth) <= 50)
#             radian = np.arctan((Data.Top_width)/(2* Data.Depth))
#             condition4 = (np.abs(np.degrees(radian) - angle) <= ang_diff)
            index = (np.where(condition0 & condition1 & condition2 & condition3 &
                              condition4 & condition5))[0]
            indexes.extend(index.tolist())

        for i in indexes:
            radian2 = np.arctan((Data.iloc[i].Top_width-Data.iloc[i].Bot_width)/(2* Data.iloc[i].Depth))
            case = np.r_[round(np.degrees(radian2),2),Data.iloc[i].Frequency / 40., ((Data.iloc[i]).round(3))]
            result.append(case)  
        DATA = np.array(result)    
        df_results = pd.DataFrame(DATA, columns = 
    ['angle', 'Speed','Frequency', 'Amplitude', 'Passes', 'Focal_Position', 'Depth',
       'Top_width', 'Bot_width'])
        return df_results

In [36]:
GAN_result = pd.read_csv('RawData/two_widths/GANtune_NNPRed.csv')

result = ParamTable_TargetTriang(GAN_result,[30], 635, 500)


result = result[(result > 0).all(1)]

result.to_csv(r'RawData/two_widths/TestData/Triang_GAN.csv', header=True, index = False)

result

,angle,Speed,Frequency,Amplitude,Passes,Focal_Position,Depth,Top_width,Bot_width
0,22.68,21.183025,847.321,0.531,38.0,93.199,631.747,535.666,7.681
1,20.45,21.077700,843.108,0.461,79.0,93.198,633.785,472.865,0.181
2,22.59,24.843525,993.741,0.517,88.0,93.200,636.473,536.725,7.087
3,20.95,21.229800,849.192,0.497,88.0,93.200,662.365,509.152,1.921
4,22.13,21.129725,845.189,0.494,35.0,93.198,609.168,496.680,1.284
5,20.69,20.609175,824.367,0.495,88.0,93.198,669.813,506.242,0.210
6,22.65,25.186900,1007.476,0.504,77.0,93.200,624.526,523.734,2.636
7,22.71,21.963925,878.557,0.519,38.0,93.200,620.218,525.140,5.884
8,22.69,21.152975,846.119,0.537,40.0,93.200,643.290,542.658,4.661
9,20.63,21.211450,848.458,0.485,99.0,93.200,656.121,495.521,1.612
10,20.22,21.379150,855.166,0.450,93.0,93.198,621.077,460.933,3.306
11,22.32,14.078925,563.157,0.513,33.0,92.667,624.518,521.119,8.385
12,22.25,20.708225,828.329,0.507,34.0,93.200,611.456,508.401,8.015
13,21.79,21.059175,842.367,0.469,32.0,93.200,588.023,470.392,0.283
14,20.42,21.269350,850.774,0.484,120.0,93.200,663.544,494.302,0.312